# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

version: "3.7"

volumes:
  mainflux-mqtt-redis-volume:

services:
  nginx:
    depends_on:
      - mqtt-adapter

  mqtt-redis:
    image: redis:5.0-alpine
    container_name: mainflux-mqtt-redis
    restart: always
    networks:
      - mainflux-base-net
    volumes:
      - mainflux-mqtt-redis-volume:/data

  mqtt-adapter:
    image: isuciu0/mainflux-mqtt:29-10-2020
    container_name: mainflux-mqtt
    restart: always
    depends_on:
      - things
      - nats
      - mqtt-redis
    environment:
      MF_MQTT_ADAPTER_LOG_LEVEL: ${MF_MQTT_ADAPTER_LOG_LEVEL}
      MF_MQTT_INSTANCE_ID: mqtt-adapter-1
      MF_MQTT_ADAPTER_PORT: ${MF_MQTT_ADAPTER_PORT}
      MF_MQTT_ADAPTER_WS_PORT: ${MF_MQTT_ADAPTER_WS_PORT}
      MF_MQTT_ADAPTER_REDIS_HOST: mqtt-redis
      MF_MQTT_ADAPTER_ES_HOST: es-redis
      MF_MQTT_ADAPTER_CA_CERTS: ${MF_MQTT_ADAPTER_CA_CERTS}
      MF_MQTT_ADAPTER_CLIENT_TLS: ${MF_MQTT_ADAPTER_CLIENT_TLS}
      MF_NATS_URL: ${MF_NATS_URL}
      MF_THINGS_URL: things:${MF_THINGS_AUTH_GRPC_PORT}
      MF_JAEGER_URL: ${MF_JAEGER_URL}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    ports:
      - 18831:${MF_MQTT_ADAPTER_PORT}
      - 8881:${MF_MQTT_ADAPTER_WS_PORT}
    networks:
      - mainflux-base-net
